name: Master
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 8 1 * *'
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Running
      run: |
        echo "Running!"
