name: Daily Commit Automation

on:
  schedule:
    - cron: '0 8 * * *'  # Runs every day at 08:00 UTC
  workflow_dispatch:      # Allow manual run too

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Commit using 24f1001518@ds.study.iitm.ac.in
        run: |
          echo "Automated update at $(date)" >> daily-log.txt
          git config --local user.email "24f1001518@ds.study.iitm.ac.in"
          git config --local user.name "GitHub Actions Bot"
          git add daily-log.txt
          git commit -m "Automated daily commit" || echo "No changes to commit"
          git push
